'use strict';
// Shortcuts to DOM Elements.
// var elements = function(){
//      console.log('DomEls')
var domEl = {
    sideNav: document.getElementById('mySidenav'),
    card: document.getElementsByClassName('card'),
    main: document.getElementById('main'),
    hamburgerButton: document.getElementById('hamburgerButton'),
    aboutCardOpenButton: document.getElementById('aboutCardOpen'),
    aboutCardCloseButton: document.getElementById('aboutCardCloseButton'),
    aboutCard: document.getElementById('aboutCard'),
    libraryCard: document.getElementById('libraryCard'),
    blogCard: document.getElementById('blogCard'),
    quals: document.getElementById('quals'),
    expandButtons: document.getElementsByClassName('expandButton'),
    qualifications: document.getElementById('qualifications'),
    projects: document.getElementById('projects'),
    history: document.getElementById('history'),
    education: document.getElementById('education'), 
    projectTable: document.getElementById('projectTable'),
    menuButton: document.getElementById('menuButton'),
    aboutLink: document.getElementById('aboutLink'),
    blogLink: document.getElementById('blogLink'),
    libraryLink: document.getElementById('libraryLink'),
    contactLink: document.getElementById('contactLink'),
    homeLink: document.getElementById('homeLink'),
    blogCardOpenButton: document.getElementById('blogCardOpenButton'),
    blogCardCloseButton: document.getElementById('blogCardCloseButton'),
    blogPosts: document.getElementById('blog-posts'),
    blogPara: document.getElementsByClassName('blogPara'),
    skillsButton: document.getElementById('skillsButton'),
    projectsButton: document.getElementById('projectsButton'),
    slideTab: document.getElementsByClassName('tabOne'),
    libraryCardOpenButton: document.getElementById('libraryCardOpen'),
    libraryCardCloseButton: document.getElementById('libraryCardCloseButton'),
    cardContainer: document.getElementById('cardContainer'),
    delkoproLink: document.getElementById('Current'),
    messageFabButton: document.getElementById('messageFabButton'),
    messageContainer: document.getElementById('messageContainer'),
    inputSection: document.getElementsByClassName('input-subject'),
    inputLabel: document.getElementsByClassName('input-label'),
    messagePanel: document.getElementsByClassName('message-panel'),
    libraryList: document.getElementById('libraryList'),
    closeMessageCard: document.getElementById('closeMessageCard'),
    overlay: document.getElementById('overlay'),
    sendMessageButton: document.getElementById('sendMessageButton'),
    messageForm: document.getElementById('messageForm'),
    closeBlogActive: document.getElementsByClassName('closeBlogButton'),
    fabToolButton: document.getElementById('fabTool'),
    fabGreen: document.getElementById('successFabGreen'),
    overlay: document.getElementById('overlay'),
    email: document.getElementsByName('email'),
    subject: document.getElementsByName('subject'),
    infoLink: document.getElementById('infoLink'),
    infoCard: document.getElementById('infoCard'),
    slideMainButton: document.getElementsByClassName('tabTwo'),
    homeImage: document.getElementById('homeImage'),
    welcomeAnimButton : document.getElementById('welcomeAnimButton'),
    tabsSection: document.getElementsByClassName('tabs'),
    headerText: document.getElementById('headerText'),
    highlightDiv: document.getElementById('highlightDiv'),
    highlightText: document.getElementById('highlightText'),
    openAnimOne: document.getElementById('openAnimOne'),
    openCircleRight: document.getElementById('openCircleRight'),
    openCircle: document.getElementById('openCircle'),
    fabTwo: document.getElementsByClassName('fab-blue-ripple'),
    fabPanelButton: document.getElementById('fabPanelButton'),
    fabToolTwo: document.getElementById('fabToolTwo')    
}
// return domEl;

// }